if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
fi

export DOTFILES="$HOME/dotfiles"
export PATH="$DOTFILES/bin:$HOME/.local/bin:$HOME/bin:$PATH"