HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000

setopt appendhistory
setopt histignorealldups
setopt sharehistory
setopt autocd
setopt interactivecomments

mkdir -p "$HOME/.cache/zsh"

autoload -Uz compinit
compinit -d "$HOME/.cache/zsh/zcompdump"

autoload -Uz colors && colors

PROMPT='%F{green}%n@%m%f:%F{blue}%~%f %# '

alias ll='ls -lah'
alias la='ls -A'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='grep --color=auto'

if command -v eza >/dev/null 2>&1; then
    alias ls='eza --group-directories-first'
    alias tree='eza --tree'
fi

if command -v bat >/dev/null 2>&1; then
    alias cat='bat --paging=never'
fi

mkcd() {
    mkdir -p -- "$1" && cd -- "$1"
}

if [ -f "$HOME/.zshrc.local" ]; then
    . "$HOME/.zshrc.local"
fi